### ISSUE TITLE
R Package Checklist 

### ISSUE THREAD

**Issue by caesarw0** [UBC-MDS/sanityzeR#4]
## Checklist for R package deliverables

- [x] Create [project structure for the R package](https://r-pkgs.org/whole-game.html)
o	https://github.com/UBC-MDS/sanityzeR

- [x] 	The name of the repository should be relevant to the package/project topics.
o	Python package name - [sanityze](https://github.com/UBC-MDS/sanityze)
o	R package name - [sanityzeR](https://github.com/UBC-MDS/sanityzeR)

- [x] For now choose the [MIT license](https://github.com/UBC-MDS/sanityzeR/blob/main/LICENSE.md). 

- [x] Use [usethis::use_code_of_conduct](https://usethis.r-lib.org/reference/use_code_of_conduct.html) to add a [code of conduct](https://github.com/UBC-MDS/sanityzeR/blob/main/CODE_OF_CONDUCT.md). You may want to customize it further to suit your group.

- [x] Add the team members as authors to the [DESCRIPTION](https://github.com/UBC-MDS/sanityzeR/blob/main/DESCRIPTION) file.

- [x] Use [usethis::use_tidy_contributing()](https://usethis.r-lib.org/reference/tidyverse.html) to add a [CONTRIBUTING.md](https://github.com/UBC-MDS/sanityzeR/blob/main/CONTRIBUTING.md) file to your package. This file will live in .github and it will create that folder if it does not already exist. Edit the boiler plate document this gives to to reflect your contribution strategy that your team has agreed upon.

- [x] Outline the package you would like to build in the [README.Rmd](https://github.com/UBC-MDS/sanityzeR/blob/main/README.md) file.

## R package function specifications

- [x] write [R function documentation](https://github.com/UBC-MDS/sanityzeR/tree/main/R) that will serve as specifications, set-up empty functions (with appropriate function names), write function documentation

**Comment by caesarw0** [comment]
closing issue - deliverables checked
